version: "3.7"

services:
    app:
        image: "laratest/app:${TAG:-latest}"
        build:
            args:
                user: testusr
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./src:/var/www
        networks:
            - test-network

    web:
        image: nginx:1.19.4
        container_name: test-nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
        volumes:
            - ./src:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - test-network

    db:
        image: mysql:5.7
        container_name: test-db
        restart: unless-stopped
        ports:
            - ${SERVER_PORT_DB:-3306}:3306
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=San_Romilla
            - MYSQL_USER=${DB_USERNAME:-homestead}
            - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
        networks:
            - test-network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - ${PHPMYADMIN_PORT_DB:-8080}:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=test-db
            - PMA_USER=${DB_USERNAME:-homestead}
            - PMA_PASSWORD=${DB_PASSWORD:-secret}
        networks:
            - test-network
#   phpmyadmin:
#       image: phpmyadmin
#       restart: always
#       ports:
#           - ${PHPMYADMIN_PORT_DB:-8080}:80
#       environment:
#           - PMA_ARBITRARY=1
#           - PMA_HOST=2daw.esvirgua.com
#           - PMA_DATABASE=user2daw_BD1-03
#           - PMA_USER=user2daw_03
#           - PMA_PASSWORD=Z~yIhDg@^IS_
#       networks:
#           - test-network

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: "none"
        ports:
            - ${MAIL_PORT:-1025}:1025
            - ${MAILHOG_PORT:-8025}:8025
        networks:
            - test-network

    npm:
      image: node:16.14.2
      container_name: npm
      volumes:
        - ./src:/var/www
      ports:
        - 3000:3000
        - 3001:3001
      working_dir: /var/www
      entrypoint: ["npm"]
      networks:
        - test-network

networks:
    test-network:
        driver: bridge

volumes:
    dbdata:
